### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by telatin** [lskatz/fasten#20]
Hello pips,
I open this issue to keep track of the review.

**Benchmark: version of the tools**
I started reproducing the benchmark and wanted to know if you could share the exact version of the programs used in your benchmark. I made an environment with the latest version of Fasten, SeqTK, Seqkit, SeqFu, fastx but maybe it's better to synchronise this (and to mention the versions used in the paper)

---
https://github.com/openjournals/joss-reviews/issues/6030

**Comment by telatin** [comment]
Note: I made PR #21, fixing typos and adding SeqFu to the pool.

Please, note that the review progress is independent of this and upcoming PRs

**Comment by telatin** [comment]
Hi @lskatz, bumping the request for the tools version. Apologies if I lost the info

**Comment by lskatz** [comment]
Hi sorry, I'm not ignoring this. I just have a holiday this week and I'll be able to address this next week.

**Comment by lskatz** [comment]
CC @bovee

* Fasten 0.7.1
* SeqTK 1.0-r31
* seqkit 2.5.1
* Seq-Fu 1.20.0
* fastx-toolkit 0.0.13

These are the versions I used, but I can update to the latest if/where you see the opportunity.

**Comment by bovee** [comment]
Following up, I was able to reproduce (modulo seqfu) the performance figure with the following on a quad core Intel Core i7-7700HQ with 16 Gb RAM running Manjaro Linux (kernel 5.10.199):
 - Fasten v0.7.2
 - seqtk 1.3-r106
 - seqkit v2.5.1
 - FASTX Toolkit 0.0.14
 - BBMap 39.06
 - jellyfish 2.3.1

Thanks for the benchmark scripts which made this much easier. For documentation in the paper, it might be good to include the hardware you're running the benchmarks on too?

**Comment by telatin** [comment]
Hi Lee,
my apologies for abandoning the review, the hiatus was longer than I thought.

I started checking the tests (note that I made a Makefile to automate building and tests, see https://github.com/telatin/fasten/tree/patch-2, if you want I can make a PR to add it but it depends on your style.)

In adding missing tests I noticed that `fasten_inspect` seems to work in paired mode by default:

```bash
cat testdata/four_reads.fasta | ./target/release/fasten_inspect 
```
gives:
```text
>read0 id-at:0 seq-length:100 seq-invalid-chars: id-plus:0 qual-invalid-chars: avg-qual:38.16 qual-length:100 read-pair:1
AAAGTGCTCTTAACTTGTCCCGCTCCACATCAGCGCGACATCAATCGACATTAAACCGAGTATCTTGTCAGCCTGGGGTGACGATGCGTCCCATTAAAGT
>read1
TCTCATAGGGCTAACGCCAGAATCCCTCCATCGGTGTTTAAGGTGCCAAACACGATGGACCAAGTTATAGGGCTGACTATTAAACTATGGGGCCGGAAAC
>read2 id-at:0 seq-length:100 seq-invalid-chars: id-plus:0 qual-invalid-chars: avg-qual:39.60 qual-length:100 read-pair:1
GTTAGGAATTGAGGCCCTGGGGTCTGTGACGTCCGCGTGTAATATGAAAAACCAATATAATCAACTGTCCCACGCAATTATAAGCCGTAGTTCAACTTCG
>read3
CACGCGTACGTAGCAATTCCAACCTCGTTTCCTCAGTCTTCTAAGGAGGAAATGTGAGGTGATGTGTCTTCGTGACCTTTGGGCTTAACTCTCATAGAGA
```

i.e. no insights printed for read1 and read3

**Comment by telatin** [comment]
In a PR added some minimal tests #30
