### ISSUE TITLE
Feature: Add command to convert to interleaved format and back from interleaved format back to 2 FASTQ files.

### ISSUE THREAD

**Issue by ghuls** [lskatz/fasten#27]
Add command to convert to interleaved format and back from interleaved format back to 2 FASTQ files for paired-end data, so they can be used at the beginning and end of a fasten pipeline.

**Comment by lskatz** [comment]
Hi @ghuls, thank you for trying out Fasten. To convert back to R1/R2, you can use `fasten_shuffle -d` which is documented here: <https://lskatz.github.io/fasten/fasten_shuffle/index.html#deshuffling>.  E.g.,

```bash
cat interleaved.fastq | fasten_shuffle -d -1 1.fastq -2 2.fastq
gzip 1.fastq 2.fastq
```

Let me know if this helps!
