### ISSUE TITLE
docs on what fasten_validate does?

### ISSUE THREAD

**Issue by kapsakcj** [lskatz/fasten#3]
I'm curious as to what fasten_validate checks on fastq files. I think it would be useful to have a little blurb or bullet points on what is validated when running that tool.

Just a thought, nothing urgent!

**Comment by lskatz** [comment]
Finally done in #9 !  https://lskatz.github.io/fasten/fasten_validate/index.html

**Comment by kapsakcj** [comment]
Sweet! Love the new docs! Nice work
