### ISSUE TITLE
[suggestion] Document, eventually enforce, input format

### ISSUE THREAD

**Issue by telatin** [lskatz/fasten#32]
I would specify when a tool supports FASTA and FASTQ or only FASTQ as input, including in the description (the `--help` page).

It's self-explanatory to have quality-related functions not working on FASTA files. Still, some tools like fasten_sort do not work on FASTA file, but there's no evident mention and no input validation.

I understand that sometimes the philosophy of keeping it simple can be the right thing to do; in this case, just a line in the helpfile would suffice :)

**Comment by lskatz** [comment]
Addressed in 0808178..e41ca44 but yes I think it would be good to make sure it is reinforced better.
