### ISSUE TITLE
fastq/fastq mergepe

### ISSUE THREAD

**Issue by jianshu93** [lskatz/fasten#35]
Hi team,

Just wonder there can be a merge command like seqtk mergepe to interleave and deinterleave fastq/fasta files. I imagine it can be very useful.

Thanks,

Jianshu

**Comment by lskatz** [comment]
Hi Jianshu, that command is `fasten_shuffle` and the documentation is here: <https://lskatz.github.io/fasten/fasten_shuffle/>. Let me know if I can clarify any more.
